# Generated by Django 5.0.2 on 2025-03-01 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azbankgateways", "0005_alter_bank_bank_type_alter_bank_created_at_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financiallogs",
            name="tracing_code",
        ),
        migrations.AlterField(
            model_name="financiallogs",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_transaction",
                to="azbankgateways.bank",
            ),
        ),
    ]
