# Generated by Django 5.0.2 on 2025-03-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_financiallogs_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financiallogs",
            name="transaction",
        ),
    ]
