# Generated by Django 5.0.2 on 2025-03-01 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azbankgateways", "0005_alter_bank_bank_type_alter_bank_created_at_and_more"),
        ("finance", "0004_remove_financiallogs_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="financiallogs",
            name="transaction",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="azbankgateways.bank",
            ),
            preserve_default=False,
        ),
    ]
