# Generated by Django 5.0.2 on 2025-03-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_financiallogs_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="financiallogs",
            name="status",
            field=models.CharField(default="Pending", max_length=10),
        ),
    ]
