# Generated by Django 4.0.7 on 2024-11-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('school_code_num', models.CharField(max_length=100)),
                ('applicant_count', models.IntegerField(default=0)),
            ],
        ),
    ]
