# Generated by Django 4.0.7 on 2025-02-21 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=100)),
                ('school_code_num', models.CharField(max_length=100, unique=True)),
                ('creator_employee_info', models.JSONField()),
                ('address', models.TextField()),
                ('requests_count', models.IntegerField(default=0)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
