# Generated by Django 4.0.7 on 2024-11-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='applicant_count',
            new_name='requests_count',
        ),
        migrations.AddField(
            model_name='school',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code_num',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
