# Generated by Django 4.0.7 on 2024-11-09 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0003_school_created_at_school_groups_school_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='school',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
        migrations.RemoveField(
            model_name='school',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='creator_employee_info',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='school',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
