# Generated by Django 4.0.7 on 2024-11-21 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0004_remove_school_groups_remove_school_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
