version: "3.9"

services:
  db:
    image: docker-mirror.kubarcloud.com/postgres:14.1
    container_name: postgres_sorayande
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sorayandeh
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456789
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for database

  rabbitmq:
    image: docker-mirror.kubarcloud.com/rabbitmq:alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  django:
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    container_name: django-sorayande
    command: ./docker/web_entrypoint.sh
    environment:
      - DATABASE_URL=psql://root:123456789@db:5432/sorayandeh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

volumes:
  postgres_data:  # Define named volume for database persistence
