# Generated by Django 4.0.7 on 2025-02-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='steel_needed_money',
            field=models.IntegerField(blank=True, null=True, verbose_name='Steel Needed Money'),
        ),
    ]
