# Generated by Django 5.0.2 on 2025-03-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0003_campaign_steel_needed_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="steel_needed_money",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="participants",
            name="participation_type",
            field=models.CharField(verbose_name="Participation Type"),
        ),
    ]
