# Generated by Django 5.0.2 on 2025-03-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0005_alter_campaign_steel_needed_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="steel_needed_money",
            field=models.IntegerField(verbose_name="steel_needed_money"),
        ),
    ]
