# Generated by Django 4.0.7 on 2024-11-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
