# Generated by Django 4.0.7 on 2025-02-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
    ]
