# Generated by Django 4.0.7 on 2024-11-07 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='info',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_company',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='roll',
            field=models.CharField(choices=[('pe', 'person'), ('co', 'company'), ('ap', 'applicant')], default=None, max_length=20, verbose_name='Roll number'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=100, unique=True)),
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_position', models.CharField(max_length=100)),
                ('company_registration_number', models.CharField(max_length=20)),
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
